apiVersion: batch/v1
kind: Job
metadata:
  name: canvas-db-init
  namespace: canvas
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: khanhdev13/canvas-lms:latest

          envFrom:
            - secretRef:
                name: canvas-secret

          env:
            - name: RAILS_ENV
              value: production

            # 🔥 IMPORTANT: non-interactive setup
            - name: CANVAS_LMS_ADMIN_EMAIL
              value: admin@canvas.com

            - name: CANVAS_LMS_ADMIN_PASSWORD
              value: Admin123!

            - name: CANVAS_LMS_ACCOUNT_NAME
              value: Canvas

            # optional but good practice
            - name: CANVAS_LMS_STATS_COLLECTION
              value: opt_out

          command:
            - sh
            - -c
            - |
              echo "⏳ Running FULL Canvas initialization..."

              bundle exec rake db:initial_setup

              echo "✅ Canvas DB fully initialized"

          volumeMounts:
            - name: canvas-config
              mountPath: /usr/src/app/config/database.yml
              subPath: database.yml

            - name: canvas-config
              mountPath: /usr/src/app/config/redis.yml
              subPath: redis.yml

            - name: canvas-config
              mountPath: /usr/src/app/config/security.yml
              subPath: security.yml

      volumes:
        - name: canvas-config
          configMap:
            name: canvas-config