apiVersion: batch/v1
kind: Job
metadata:
  name: canvas-db-init
  namespace: canvas
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: khanhdev13/canvas-lms:latest

          envFrom:
            - secretRef:
                name: canvas-secret

          env:
            - name: RAILS_ENV
              value: production

          command:
            - sh
            - -c
            - |
              echo "⏳ Running DB migrate..."
              bundle exec rails db:migrate &&

              echo "⏳ Running initial setup..."
              export CANVAS_LMS_ADMIN_EMAIL=admin@canvas.com
              export CANVAS_LMS_ADMIN_PASSWORD=Admin123!
              export CANVAS_LMS_ADMIN_NAME=Admin

              bundle exec rake db:initial_setup

          volumeMounts:
            - name: canvas-config
              mountPath: /usr/src/app/config/database.yml
              subPath: database.yml

            - name: canvas-config
              mountPath: /usr/src/app/config/redis.yml
              subPath: redis.yml

            - name: canvas-config
              mountPath: /usr/src/app/config/security.yml
              subPath: security.yml

      volumes:
        - name: canvas-config
          configMap:
            name: canvas-config