apiVersion: batch/v1
kind: Job
metadata:
  name: canvas-db-init
  namespace: canvas
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: khanhdev13/canvas-lms:latest

          envFrom:
            - secretRef:
                name: canvas-secret

          env:
            - name: RAILS_ENV
              value: production

          command:
            - sh
            - -c
            - |
              echo "⏳ Running DB migrate..."
              bundle exec rails db:migrate &&

              echo "⏳ Seeding basic data..."
              bundle exec rails db:seed &&

              echo "⏳ Creating admin user..."
              bundle exec rails runner "
                # Ensure root account exists
                a = Account.default || Account.create!(
                  name: 'Default Account'
                );

                # Ensure user
                u = User.find_or_initialize_by(name: 'Admin');

                if u.new_record?
                  u.short_name = 'Admin';
                  u.sortable_name = 'Admin';
                  u.workflow_state = 'active';
                  u.save!;
                end;

                # Ensure login
                p = Pseudonym.find_or_initialize_by(unique_id: 'admin@canvas.com');

                if p.new_record?
                  p.user = u;
                  p.password = 'Admin123!';
                  p.password_confirmation = 'Admin123!';
                  p.workflow_state = 'active';
                  p.save!;
                end;

                # Ensure admin role
                admin_role = Role.get_built_in_role('AccountAdmin', root_account_id: a.id);

                AccountUser.find_or_create_by!(
                  user: u,
                  account: a,
                  role: admin_role
                );

                puts '✅ Admin ensured (idempotent)'
              "

          volumeMounts:
            - name: canvas-config
              mountPath: /usr/src/app/config/database.yml
              subPath: database.yml

            - name: canvas-config
              mountPath: /usr/src/app/config/redis.yml
              subPath: redis.yml

            - name: canvas-config
              mountPath: /usr/src/app/config/security.yml
              subPath: security.yml

      volumes:
        - name: canvas-config
          configMap:
            name: canvas-config