apiVersion: v1
kind: Secret
metadata:
  name: canvas-secret
  namespace: canvas
type: Opaque
stringData:
  SECRET_KEY_BASE: "adbb56b6d277579a4c24584e5fd49c9adf8cc52281edfe3d958bcc0e4488ae7b"
  ENCRYPTION_KEY: "adbb56b6d277579a4c24584e5fd49c9adf8cc52281edfe3d958bcc0e4488ae7b"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "canvas_production"
  DB_USER: "canvas"
  DB_PASSWORD: "password"
  REDIS_URL: "redis://redis:6379/0"
  CANVAS_DOMAIN: "canvas.io.vn"
  CANVAS_FORCE_SSL: "false"
  CANVAS_OUTGOING_MAIL_ADDRESS: "no-reply@canvas.io.vn"
  CANVAS_SESSION_SECURE: "false"
  CANVAS_COOKIE_SAME_SITE: "Lax"
  security.yml: |
    production:
      encryption_key: <%= ENV["ENCRYPTION_KEY"] %>
      signing_secret: <%= ENV["SECRET_KEY_BASE"] %>
      jwt_encryption_key: <%= ENV["ENCRYPTION_KEY"] %>
      jwt_encryption_keys:
        - <%= ENV["ENCRYPTION_KEY"] %>
